//@ts-check

import Head from "next/head";
import React from "react";
// import Header from "../components/ManualHeader";
import Header from "../components/Header";
import Body from "../components/Body";
import { useMoralis } from "react-moralis";

export default function Home() {
  const supportedChains = ["31337", "5"];
  const { isWeb3Enabled, chainId } = useMoralis();

  let id = parseInt(chainId ? chainId : "0x0");
  if (id === 1337) {
    id = 31337;
  }
  let strId = id.toString();

  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ margin: 0 }}>
        <Header />
        <div className="main-body">
          {!supportedChains.includes(strId) && isWeb3Enabled ? (
            <div className="not-supported">Unsupported chain</div>
          ) : (
            <Body />
          )}
        </div>
      </main>
    </>
  );
}
